import type { PluginManifest } from "../../shared/types";

/**
 * 同梱(ビルトイン)プラグインのマニフェスト一覧。
 * 実際の UI 実装は src/plugins/builtin/<id> 配下にあり、renderer 側の PluginRegistry が
 * この manifest.entry と対応する id をキーに静的インポートで解決する。
 * サードパーティ製プラグインを増やす際もこの形式の manifest.json を追加していく想定。
 */
export const BUILTIN_MANIFESTS: PluginManifest[] = [
  {
    id: "notes",
    name: "メモ",
    version: "0.1.0",
    description: "シンプルな Markdown 対応メモ",
    icon: "NotebookPen",
    category: "life",
    entry: "notes",
    enabled: true,
    builtin: true,
  },
  {
    id: "todo",
    name: "ToDo",
    version: "0.1.0",
    description: "タスク管理・チェックリスト",
    icon: "ListChecks",
    category: "life",
    entry: "todo",
    enabled: true,
    builtin: true,
  },
  {
    id: "ai-chat",
    name: "AIチャット",
    version: "0.1.0",
    description: "OpenAI/Anthropic/Gemini/ローカルLLMと対話",
    icon: "Sparkles",
    category: "ai",
    entry: "ai-chat",
    enabled: true,
    builtin: true,
  },
  {
    id: "checklist",
    name: "チェックリスト",
    version: "0.1.0",
    description: "複数のチェックリストを管理",
    icon: "ClipboardList",
    category: "life",
    entry: "checklist",
    enabled: true,
    builtin: true,
  },
  {
    id: "calendar",
    name: "カレンダー",
    version: "0.1.0",
    description: "月表示カレンダーと予定管理",
    icon: "CalendarDays",
    category: "life",
    entry: "calendar",
    enabled: true,
    builtin: true,
  },
  {
    id: "habits",
    name: "習慣管理",
    version: "0.1.0",
    description: "毎日の習慣を記録・連続記録を可視化",
    icon: "Flame",
    category: "life",
    entry: "habits",
    enabled: true,
    builtin: true,
  },
  {
    id: "pomodoro",
    name: "ポモドーロタイマー",
    version: "0.1.0",
    description: "集中時間と休憩を管理するタイマー",
    icon: "Timer",
    category: "life",
    entry: "pomodoro",
    enabled: true,
    builtin: true,
  },
  {
    id: "stopwatch",
    name: "ストップウォッチ",
    version: "0.1.0",
    description: "経過時間の計測とラップ記録",
    icon: "Watch",
    category: "life",
    entry: "stopwatch",
    enabled: true,
    builtin: true,
  },
  {
    id: "timer",
    name: "タイマー",
    version: "0.1.0",
    description: "シンプルなカウントダウンタイマー",
    icon: "AlarmClock",
    category: "life",
    entry: "timer",
    enabled: true,
    builtin: true,
  },
  {
    id: "calculator",
    name: "電卓",
    version: "0.1.0",
    description: "四則演算の電卓",
    icon: "Calculator",
    category: "life",
    entry: "calculator",
    enabled: true,
    builtin: true,
  },
  {
    id: "unit-converter",
    name: "単位変換",
    version: "0.1.0",
    description: "長さ・重さ・温度の単位変換",
    icon: "Ruler",
    category: "life",
    entry: "unit-converter",
    enabled: true,
    builtin: true,
  },
  {
    id: "qr-generator",
    name: "QRコード生成",
    version: "0.1.0",
    description: "テキストやURLからQRコードを生成",
    icon: "QrCode",
    category: "life",
    entry: "qr-generator",
    enabled: true,
    builtin: true,
  },
  {
    id: "qr-reader",
    name: "QRコード読み取り",
    version: "0.1.0",
    description: "画像からQRコードを読み取り",
    icon: "ScanLine",
    category: "life",
    entry: "qr-reader",
    enabled: true,
    builtin: true,
  },
  {
    id: "password-generator",
    name: "パスワードジェネレーター",
    version: "0.1.0",
    description: "安全なランダムパスワードを生成",
    icon: "KeyRound",
    category: "life",
    entry: "password-generator",
    enabled: true,
    builtin: true,
  },
  {
    id: "world-clock",
    name: "世界時計",
    version: "0.1.0",
    description: "複数のタイムゾーンの現在時刻を表示",
    icon: "Globe2",
    category: "life",
    entry: "world-clock",
    enabled: true,
    builtin: true,
  },
  {
    id: "ai-tutor",
    name: "AI家庭教師",
    version: "0.1.0",
    description: "科目を選んでAIに質問できる家庭教師チャット",
    icon: "GraduationCap",
    category: "study",
    entry: "ai-tutor",
    enabled: true,
    builtin: true,
  },
  {
    id: "vocabulary",
    name: "英単語帳",
    version: "0.1.0",
    description: "単語・意味・例文を登録して暗記練習",
    icon: "BookOpen",
    category: "study",
    entry: "vocabulary",
    enabled: true,
    builtin: true,
  },
  {
    id: "flashcards",
    name: "暗記カード",
    version: "0.1.0",
    description: "表裏のあるカードで反復学習",
    icon: "Layers",
    category: "study",
    entry: "flashcards",
    enabled: true,
    builtin: true,
  },
  {
    id: "quiz-generator",
    name: "クイズ生成",
    version: "0.1.0",
    description: "テキストやPDFからAIがクイズを自動生成",
    icon: "FileQuestion",
    category: "study",
    entry: "quiz-generator",
    enabled: true,
    builtin: true,
  },
  {
    id: "study-timer",
    name: "学習時間記録",
    version: "0.1.0",
    description: "科目別に学習時間を計測・記録",
    icon: "Hourglass",
    category: "study",
    entry: "study-timer",
    enabled: true,
    builtin: true,
  },
  {
    id: "grades",
    name: "成績管理",
    version: "0.1.0",
    description: "テストの点数を記録し科目別平均を可視化",
    icon: "Award",
    category: "study",
    entry: "grades",
    enabled: true,
    builtin: true,
  },
  {
    id: "study-notes",
    name: "Markdownノート",
    version: "0.1.0",
    description: "科目別に整理できるMarkdown対応ノート",
    icon: "NotebookText",
    category: "study",
    entry: "study-notes",
    enabled: true,
    builtin: true,
  },
  {
    id: "study-stats",
    name: "勉強統計",
    version: "0.1.0",
    description: "学習時間・クイズ正答率・成績をまとめて確認",
    icon: "BarChart3",
    category: "study",
    entry: "study-stats",
    enabled: true,
    builtin: true,
  },
  {
    id: "file-browser",
    name: "ファイルブラウザ",
    version: "0.1.0",
    description: "フォルダ閲覧・検索・お気に入り登録",
    icon: "FolderOpen",
    category: "files",
    entry: "file-browser",
    enabled: true,
    builtin: true,
  },
  {
    id: "file-tools",
    name: "ファイルツール",
    version: "0.1.0",
    description: "ZIP圧縮/解凍・重複検索・ハッシュ確認・ファイル比較",
    icon: "Archive",
    category: "files",
    entry: "file-tools",
    enabled: true,
    builtin: true,
  },
  {
    id: "pdf-tools",
    name: "PDFツール",
    version: "0.1.0",
    description: "PDFの閲覧・結合・分割",
    icon: "FileText",
    category: "document",
    entry: "pdf-tools",
    enabled: true,
    builtin: true,
  },
  {
    id: "document-viewer",
    name: "Word/Excel閲覧",
    version: "0.1.0",
    description: "Word文書とExcelファイルをその場で閲覧",
    icon: "FileSpreadsheet",
    category: "document",
    entry: "document-viewer",
    enabled: true,
    builtin: true,
  },
  {
    id: "text-editor",
    name: "テキストエディター",
    version: "0.1.0",
    description: "プレーンテキスト/Markdownファイルの編集",
    icon: "FileEdit",
    category: "document",
    entry: "text-editor",
    enabled: true,
    builtin: true,
  },
  {
    id: "image-editor",
    name: "画像編集",
    version: "0.1.0",
    description: "リサイズ・クロップ・回転・形式変換・ICO生成",
    icon: "Image",
    category: "image",
    entry: "image-editor",
    enabled: true,
    builtin: true,
  },
  {
    id: "image-ocr",
    name: "画像OCR",
    version: "0.1.0",
    description: "画像内の文字をテキストとして抽出",
    icon: "ScanText",
    category: "image",
    entry: "image-ocr",
    enabled: true,
    builtin: true,
  },
  {
    id: "video-tools",
    name: "動画ツール",
    version: "0.1.0",
    description: "動画変換・トリミング・GIF作成・サムネイル生成",
    icon: "Video",
    category: "video",
    entry: "video-tools",
    enabled: true,
    builtin: true,
  },
  {
    id: "audio-tools",
    name: "音声ツール",
    version: "0.1.0",
    description: "MP3/WAV変換・ノイズ除去・音量調整",
    icon: "Music",
    category: "audio",
    entry: "audio-tools",
    enabled: true,
    builtin: true,
  },
  {
    id: "memory-match",
    name: "神経衰弱",
    version: "0.1.0",
    description: "絵柄をそろえる暇つぶしカードゲーム",
    icon: "Gamepad2",
    category: "game",
    entry: "memory-match",
    enabled: true,
    builtin: true,
  },
  {
    id: "finance",
    name: "家計簿",
    version: "0.1.0",
    description: "支出・収入の記録、予算管理、サブスクの把握、支出分析",
    icon: "Wallet",
    category: "life",
    entry: "finance",
    enabled: true,
    builtin: true,
  },
  {
    id: "realtime-chat",
    name: "リアルタイムチャット",
    version: "0.1.0",
    description: "登録不要・ルームコード/招待URL/QRで参加できるリアルタイムチャット",
    icon: "MessagesSquare",
    category: "internet",
    entry: "realtime-chat",
    enabled: true,
    builtin: true,
  },
];
